### ISSUE TITLE
Confuse with capi provisioner's manifest file

### ISSUE THREAD

**Issue by vincent-pli** [kubernetes-sigs/cluster-api-provider-nested#143]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
I'm little, seems we try to add `capi provisioner` and remove `native` and `aliyun`.

But I found we change some field in the original manifest file, for example:
- Change `pullpolicy` to `Never`

https://github.com/kubernetes-sigs/cluster-api-provider-nested/blob/ce11f3e9a73dbf2d691a4d06c5ef2d5b908620a7/virtualcluster/config/setup/all_in_one_capi.yaml#L246

https://github.com/kubernetes-sigs/cluster-api-provider-nested/blob/ce11f3e9a73dbf2d691a4d06c5ef2d5b908620a7/virtualcluster/config/setup/all_in_one_capi.yaml#L386

https://github.com/kubernetes-sigs/cluster-api-provider-nested/blob/ce11f3e9a73dbf2d691a4d06c5ef2d5b908620a7/virtualcluster/config/setup/all_in_one_capi.yaml#L470

- and disable `webhook`:
https://github.com/kubernetes-sigs/cluster-api-provider-nested/blob/ce11f3e9a73dbf2d691a4d06c5ef2d5b908620a7/virtualcluster/config/setup/all_in_one_capi.yaml#L243

Would you mind I change it back?

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-nested version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api-provider-nested/labels?q=area for the list of labels]

**Comment by christopherhein** [comment]
These changes need to migrated to support the CAPI style deployment manifest generation as we have in the base repo. This work is being tracked under #129 .
