### ISSUE TITLE
ClusterResourceSet feature does not work

### ISSUE THREAD

**Issue by wangjsty** [kubernetes-sigs/cluster-api-provider-nested#155]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

Follow the proposal guides: 
https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/20200220-cluster-resource-set.md
https://cluster-api.sigs.k8s.io/tasks/experimental-features/experimental-features.html?highlight=ClusterResourceSet#enabling-experimental-features-on-existing-management-clusters
1. Deploy two nested clusters in Kind
2. Enable ClusterResourceSet feature
3. Create secret and configmap by the samples from 20200220-cluster-resource-set.md
4. Create ClusterResourceSet by the sample from 20200220-cluster-resource-set.md

The following problem appears, but the two apiservers are running normally by kubectl command.
```
E0702 09:08:52.250697       1 controller.go:302] controller-runtime/manager/controller/clusterresourceset "msg"="Reconciler error"
 "error"="error creating client and cache for remote cluster: error creating dynamic rest mapper for remote cluster \"default/cluster-sample\":
 Get \"https://cluster-sample-apiserver:6443/api?timeout=10s\": dial tcp: lookup cluster-sample-apiserver on 10.96.0.10:53: server misbehaving"
  "name"="crs1" "namespace"="default" "reconciler group"="addons.cluster.x-k8s.io" "reconciler kind"="ClusterResourceSet"
E0702 09:07:16.064594       1 controller.go:302] controller-runtime/manager/controller/clusterresourceset "msg"="Reconciler error"
 "error"="error creating client and cache for remote cluster: error creating dynamic rest mapper for remote cluster \"default/cluster-virtual\":
 Get \"https://cluster-virtual-apiserver:6443/api?timeout=10s\": dial tcp: lookup cluster-virtual-apiserver on 10.96.0.10:53: server misbehaving"
 "name"="crs1" "namespace"="default" "reconciler group"="addons.cluster.x-k8s.io" "reconciler kind"="ClusterResourceSet"
```

**What did you expect to happen:**
The secret and configmap are deployed in nested clusters

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-nested version: v0.10
- Minikube/KIND version: kind v0.11.1
- Kubernetes version: (use `kubectl version`): v1.21.1
- OS (e.g. from `/etc/os-release`): Red Hat Enterprise Linux 8

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api-provider-nested/labels?q=area for the list of labels]

**Comment by wangjsty** [comment]
@Fei-Guo @christopherhein @charleszheng44 @gyliu513

**Comment by christopherhein** [comment]
@wangjsty can you add this information to #41 ?

**Comment by christopherhein** [comment]
/close
duplicate issue for tracking CRS.

**Comment by wangjsty** [comment]
@christopherhein I would like to track the issue by the duplicated one #41. Thanks!
