### ISSUE TITLE
Update the image on docker hub

### ISSUE THREAD

**Issue by vincent-pli** [kubernetes-sigs/cluster-api-provider-nested#165]
**User Story**
Could we update the image on docker hub, since we has address some issue recently:
I saw the last update is 15 days ago:
https://hub.docker.com/r/virtualcluster/syncer-amd64/tags?page=1&ordering=last_updated

/kind feature

**Comment by christopherhein** [comment]
@Fei-Guo @charleszheng44 do you know who owns that image?

**Comment by charleszheng44** [comment]
@christopherhein I created the registry. @vincent-pli will update the images.

**Comment by charleszheng44** [comment]
@vincent-pli pushed.

**Comment by vincent-pli** [comment]
Thanks @charleszheng44
