### ISSUE TITLE
Bump Cluster API to 0.4.0

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api-provider-nested#189]
**User Story**

As a [developer/user/operator] I would like to [high level description] for [reasons]

**Detailed Description**

There are lot of bug fix and break changes in Cluster API 0.4.0, and it also fixed some critical bugs for security as well, such as https://github.com/kubernetes-sigs/cluster-api/pull/3979 etc.

@christopherhein @Fei-Guo @charleszheng44 comments?

@wangjsty ^^

/kind feature

**Comment by christopherhein** [comment]
Sound great!

**Comment by charleszheng44** [comment]
Sounds good to me!
