### ISSUE TITLE
Leverage Knative to reduce the footprint of the control plane of tenant

### ISSUE THREAD

**Issue by vincent-pli** [kubernetes-sigs/cluster-api-provider-nested#195]
Just a very draft though, have no idea if there is any block issue for it.
I saw there is one further work in the [PDF](https://github.com/kubernetes-sigs/cluster-api-provider-nested/blob/main/virtualcluster/doc/vc-icdcs.pdf), it said we should 
`Reducing the cost of running tenant control planes`

So I think could we leverage `knative` to do it, especially for the idle tenant?

@Fei-Guo @charleszheng44 @christopherhein @gyliu513 
What do you think?

/kind feature

**Comment by Fei-Guo** [comment]
Can you provide more description about your idea? I don't immediate see how knative can help here.

**Comment by gyliu513** [comment]
@Fei-Guo I think @vincent-pli is mentioning the case here https://medium.com/ibm-cloud/using-serverless-model-to-reduce-footprint-for-your-kubernetes-openshift-platform-d06bfbeb65f2 , want to leverage knative to scale some pods to 0 if they are idle.

**Comment by Fei-Guo** [comment]
CAPN components are tricky here. We probably always need a set to be ready even if it is idle because we usually cannot tolerate the cost of restart a whole control plane in terms of latency. In the paper, I was thinking about more on system solution such as enabling host memory swap to allow overcommiting the resources of the host that runs CAPN components. The idea is that multiple VCs may not be busy at the same time so overcommitment may be a good idea to reduce the hardware cost.

**Comment by vincent-pli** [comment]
Yes, my though is we can wrapper at least `api-server` of tenant to be a `KSVC`, then it will scale to 0 when idle.
but if we can not tolerate the code start I think it will not be a choice.
@Fei-Guo @gyliu513

**Comment by christopherhein** [comment]
Yeah, cold starts of a Kube APIServer are likely too costly with informer cache priming for all objects, I'm imagining a tenant control plane running 1000's of resources having to start up, fetch the state of the world from etcd and then being able to serve the request would be too much. Interesting idea though and I wonder if there are other use cases that would fit that bill.

**Comment by charleszheng44** [comment]
> Yes, my though is we can wrapper at least `api-server` of tenant to be a `KSVC`, then it will scale to 0 when idle.
> but if we can not tolerate the cold start I think it will not be a choice.
> @Fei-Guo @gyliu513

I agree with @christopherhein. The major concern is latency, for a large cluster, it may take 10 - 20 secs to sync the cache. But if each tenant only create a few resources, then it would be a good idea to scale down the `apiserver` or even `controller-manager` to 0

**Comment by christopherhein** [comment]
@vincent-pli if this all makes sense can we close this?

**Comment by vincent-pli** [comment]
Sure, thanks everyone
