### ISSUE TITLE
VirtualCluster fail to create with "cannot find sts/apiserver in ns" on minikube running k8s 1.20.2

### ISSUE THREAD

**Issue by sriram-kannan-infoblox** [kubernetes-sigs/cluster-api-provider-nested#198]
The VirtualCluster fail to create the apiserver and the apiserver-0 is in the container creating state
`kubectl-vc create -f virtualcluster_1_nodeport.yaml -o vc.kubeconfig`
`2021/07/28 08:20:03 etcd is ready`
`cannot find sts/apiserver in ns default-e4d075-vc-sample-1: default-e4d075-vc-sample-1/apiserver is not ready in 120 seconds`

`kubectl get po -n default-e4d075-vc-sample-1`
`NAME          READY   STATUS                RESTARTS     AGE`
`apiserver-0   0/1      ContainerCreating          0          46m`
`etcd-0           1/1       Running                          1          47m`

**What steps did you take and what happened:**
Followed the step as per the virtual cluster walkthrough demo and all the steps were successful till the Create VirtualCluster.  
https://github.com/kubernetes-sigs/cluster-api-provider-nested/blob/main/virtualcluster/doc/demo.md

During the Create VirtualCluster the etcd came up fine but the apiserver-0 stayed in the ContainerCreating state.

**What did you expect to happen:**
Expected to see the apiserver and controller-manager to be in running state.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-nested version: 
- Minikube/KIND version:  minikube version: v1.21.0 
- Kubernetes version: (use `kubectl version`): 1.20.2
- OS (e.g. from `/etc/os-release`): darwin

**Comment by jichenjc** [comment]
>>>apiserver-0 0/1 ContainerCreating 0 46m

what's the reason for this creating status? I ecountered this before due to docker pull limit
but seems you are not, how about check the reason for why container creating in 46 min?
e.g describe the container for additional info?

**Comment by sriram-kannan-infoblox** [comment]
Good point, i checked the pod and the  failure is due to 
`  Warning  FailedMount  5m43s (x50 over 91m)  kubelet, minikube  MountVolume.SetUp failed for volume "front-proxy-ca" : secret "front-proxy-ca" not found`
  `Warning  FailedMount  33s (x12 over 86m)    kubelet, minikube  Unable to attach or mount volumes: unmounted volumes=[front-proxy-ca], unattached volumes=[apiserver-ca front-proxy-ca root-ca serviceaccount-rsa default-token-8xxsj]: timed out waiting for the condition`

**Comment by jichenjc** [comment]
ok, looks like the ca has issue and to my limited knowledge those ca are created by CAPN directly
@christopherhein any insight for further trouble shooting on this?

**Comment by sriram-kannan-infoblox** [comment]
Looks to me like Minikube doesn't create the certificates in the /etc/kubernetes/pki, unlike kubeadm.  Do we need frontend-proxy for the virtualcluster to work?

**Comment by gyliu513** [comment]
@sriram-kannan-infoblox this was introduced in https://github.com/kubernetes-sigs/cluster-api-provider-nested/pull/167 , can you make sure you are using latest code and build all of the images/binaries from the latest code?

**Comment by sriram-kannan-infoblox** [comment]
Hi @gyliu513,  I am only following the steps as per the walkthrough demo below and haven't tried to build the image at all.
https://github.com/kubernetes-sigs/cluster-api-provider-nested/blob/main/virtualcluster/doc/demo.md

My query was do we need the aggregate API for virtual cluster to work? I can go back few commits and try out virtual cluster in minikube if aggregate API change is not a breaking change. 

My plan is to try out virtual cluster in minikube first and then take it to actual cluster.

Thanks

**Comment by gyliu513** [comment]
@sriram-kannan-infoblox as a workaround, please remove the aggregate api support, check https://github.com/kubernetes-sigs/cluster-api-provider-nested/pull/167/files for how to remove, you only need to update the statefulset for apiserver.

The https://github.com/kubernetes-sigs/cluster-api-provider-nested/blob/main/virtualcluster/doc/demo.md need some update, as it is not using the latest image.

**Comment by jasonliu747** [comment]
> The https://github.com/kubernetes-sigs/cluster-api-provider-nested/blob/main/virtualcluster/doc/demo.md need some update, as it is not using the latest image.
Hi @gyliu513 do you have any update on this demo.md? Thanks.

**Comment by gyliu513** [comment]
> The https://github.com/kubernetes-sigs/cluster-api-provider-nested/blob/main/virtualcluster/doc/demo.md need some update, as it is not using the latest image.

@vincent-pli I recalled you opened another issue to track this? What is the status?
