### ISSUE TITLE
cluster always be Provisioned instead of running state

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-nested#199]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

**What did you expect to happen:**
follow the guide of CAPN,  ,everything is fine except cluster is provisioned instead of running
https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/src/images/bootstrap-controller.png

```
cloudusr@jitest19:~$ kubectl get nestedcontrolplanes
NAME                           READY   AGE
cluster-sample-control-plane   true    39m
cloudusr@jitest19:~$ kubectl get nestedcontrollermanagers
NAME                                     PHASE   AGE
cluster-sample-nestedcontrollermanager   Ready   40m
cloudusr@jitest19:~$ kubectl get nestedapiservers
NAME                             PHASE   AGE
cluster-sample-nestedapiserver   Ready   40m
cloudusr@jitest19:~$ kubectl get cluster
NAME             PHASE
cluster-sample   Provisioned

```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-nested version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api-provider-nested/labels?q=area for the list of labels]

**Comment by christopherhein** [comment]
I think this might be because we're not watching instead polling check out - #137

**Comment by jichenjc** [comment]
this is a wrong report

I read the wrong picture and only machine has Running phase while cluster doesn't
https://github.com/kubernetes-sigs/cluster-api/blob/master/api/v1alpha4/cluster_phase_types.go
