### ISSUE TITLE
Refresh the image on docker hub

### ISSUE THREAD

**Issue by vincent-pli** [kubernetes-sigs/cluster-api-provider-nested#212]
Please refresh the image on the docker hub: virtualcluster/manager-amd64

People will always hit this issue #198 without refresh the image with latest source code and the whole function will not work.
@charleszheng44 @christopherhein @Fei-Guo

**Comment by Fei-Guo** [comment]
@christopherhein   Should we put vc related images in CAPN image repo instead of virtualcluster dockerhub repo?

**Comment by christopherhein** [comment]
Yeah, this is in essence a dupe of #129 and #130 which is the proper place for released images.

**Comment by jasonliu747** [comment]
Any update on this issue?
/cc @christopherhein @vincent-pli @Fei-Guo
