### ISSUE TITLE
Migrate to v1beta1 contract

### ISSUE THREAD

**Issue by MartinForReal** [kubernetes-sigs/cluster-api-provider-nested#225]
**User Story**

As cluster api is moving to GA, It dropped support for v1alpha4 contract. Migration to v1beta1 is required.

**Detailed Description**

[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**

```
 clusterctl init --infrastructure nested:v0.1.0              
Fetching providers
Error: current version of clusterctl is only compatible with v1beta1 providers, detected v1alpha4 for provider infrastructure-nested

```
/kind feature

**Comment by kfox1111** [comment]
Was it fixed?
