### ISSUE TITLE
✨ Metrics for vn-agent

### ISSUE THREAD

**Issue by srirammageswaran8** [kubernetes-sigs/cluster-api-provider-nested#251]
## User Story

As an operator I would like to export metrics for vn-agent.

## Detailed Description

vn-agent does not export metrics at this point. A metrics server is to be enabled by default on the address `:9100` and allowed to be configured by the cli option `--metrics-addr` options. The metrics server can be disabled by cli option `--enable-metrics` to `false`. The metrics are default enabled.

`vn-agent` should expose the below metrics

- Instrumented API calls to super api / Kubelet. 
- Count requests with respect to host, tenantName, tenantNamespace, action and responseCode.

/kind feature

**Comment by christopherhein** [comment]
Thanks @srirammageswaran8, this makes sense to me it will be good to be able to understand the health of each vn-agent and the how they are performing.

cc @Fei-Guo & @charleszheng44  concerns or thoughts?

**Comment by Fei-Guo** [comment]
Since the vn-agent simply proxies the kublet APIs, I don't see strong need of having pprof enabled. It does make sense to add tenant related metrics in vn-agent.

**Comment by srirammageswaran8** [comment]
Updated Description and @Fei-Guo agree with you on pprof.

**Comment by atosatto** [comment]
> The metrics server can be disabled by cli option --enable-metrics to false. The metrics are default enabled.

I don't think this is necessary. Perhaps users that don't want to collect metrics can just bind `localhost`.

**Comment by christopherhein** [comment]
Issue with This an a traditional deployment the vnagent is run using host networking as a daemonset. So binding to `localhost` would still make that accessible to clustered workloads.

**Comment by atosatto** [comment]
> Issue with this is a traditional deployment the vnagent is run using host networking as a daemonset. So binding to localhost would still make that accessible to clustered workloads.

LGTM then!
