### ISSUE TITLE
Virtual Cluster k8s version

### ISSUE THREAD

**Issue by mkcetinkaya** [kubernetes-sigs/cluster-api-provider-nested#271]
Hello,

We succesfully deployed super cluster and virtual clusters. Firstly, thanks for your efforts. 

Super cluster version 1.21.9 and Virtual cluster version is 1.16.2. And our expectation was Virtual cluster version also same as super cluster (1.21.9) or something else that we can define decleratively. 

So our question is that can we define virtual cluster kubernetes version or every time it will be 1.16.2. If so, is there a way to build new container images for newer k8s versions, because only available api,server has version 1.16.2 in docker hub repository.

Thanks and regards

**Comment by mkcetinkaya** [comment]
Hi again,

Quick update. We have used upstream kubapi-server and controller-manager images (1.21.X). Successfully created vc. However could not deploy pod, it hangs at pending state and  kubernetes default service related to virtual cluster is not being created in super cluster. When we check vc-syncer logs we got below message. 

dws.go:65] failed reconcile service default/kubernetes CREATE of cluster default-915f56-vc-2 Service "kubernetes" is invalid: spec.clusterIPs: Invalid value: []string{"10.32.0.1"}: must be empty when clusterIP is empty

When we compare with 1.16 version, there is no "clusterIps" line in 1.16 and in 1.21 version there are below lines in kubernetes service in virtual cluster and I guess error is related to this.

clusterIPs: 
- 10.32.0.1

Could you give us a advice for getting rid of this error?

Thanks and regards.

**Comment by m-messiah** [comment]
Hi! We updated samples in https://github.com/kubernetes-sigs/cluster-api-provider-nested/pull/301
1.22.13 is the last version tested, but you could try anything else, as you see, the tenant cluster version is configurable

**Comment by mkcetinkaya** [comment]
Hello @m-messiah first of all thanks for the update.

We tried same version with your suggested example yaml. Virtual cluster with version 1.22.13 was deployed succesfully. However when we deploy some pods its state is in pending state and describe pod output is like that 

" Warning  FailedCreate  11s (x12 over 21s)  vc-syncer  Error creating: failed to list services from cluster default-35c1d7-vc-22 cache: service is not ready"

And also check default kubernetes service, it was created in VC but not synced to supercluster as in version 1.19 

Were you able to deploy pod to VC with version 1.22.X and any suggestion for us?

Thanks
