### ISSUE TITLE
update (virtual cluster) validation webhook registration to support admission.../v1

### ISSUE THREAD

**Issue by mghlaiel** [kubernetes-sigs/cluster-api-provider-nested#296]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
I followed the README guide to deploy a virtual cluster on kind (kubernetes v1.24) then rancher RKE (kubernetes version 1.23)
```
kubectl vc create -f https://raw.githubusercontent.com/kubernetes-sigs/cluster-api-provider-nested/main/virtualcluster/config/sampleswithspec/virtualcluster_1_nodeport.yaml -o vc-1.kubeconfig
cannot find sts/etcd in ns default-95213e-vc-sample-1: statefulsets.apps "etcd" not found
```
Logs of the `vc-manager` pod:
```
k logs -n vc-manager  pods/vc-manager-6f855758c-cr4gv

{"level":"error","ts":1659554169.9459105,"logger":"entrypoint","msg":"unable to register webhooks to the manager","error":"fail to create validating webhook configuration: no matches for kind \"ValidatingWebhookConfiguration\" in version \"admissionregistration.k8s.io/v1beta1\""}
```
**What did you expect to happen:**
A virtual cluster successfully created and kubeconfig output

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-nested version: virtual cluster
- Minikube/KIND version: kind 
- Kubernetes version: (use `kubectl version`): Major:"1", Minor:"24", GitVersion:"v1.24.3"
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.4

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api-provider-nested/labels?q=area for the list of labels]

**Comment by LuBingtan** [comment]
It seems that this issue is already fixed by this commit: https://github.com/kubernetes-sigs/cluster-api-provider-nested/commit/c9cb5b71b29945675e441b38c12b2a24d9bbba29

**But** image `virtualcluster/manager-amd64:latest` was not updated. You can build the image on your local machine, and load it to kind.

By the way, is there anyone can help to update the image `virtualcluster/manager-amd64:latest` to the latest version?
