### ISSUE TITLE
Consider extending conversations package to work with vNodes

### ISSUE THREAD

**Issue by m-messiah** [kubernetes-sigs/cluster-api-provider-nested#312]
**User Story**
As a developer today I need to make my own conversions of vNode to pNode objects, while we already have a package to do it for all other resources. I would like to have the process be more generic and transparent for any object in the cluster

/kind feature

_Originally posted by @christopherhein in https://github.com/kubernetes-sigs/cluster-api-provider-nested/pull/309#pullrequestreview-1120532105_

**Comment by christopherhein** [comment]
Thanks for filing this!
