### ISSUE TITLE
✨PersistentVolumeClaim support UWS status update

### ISSUE THREAD

**Issue by wondywang** [kubernetes-sigs/cluster-api-provider-nested#322]
**User Story**

As a user, I want to update the spec.resources.requests.storage of PVC, but I found that after updating requests.storage, status.capacity.storage is not updated synchronously, resulting in an exception when kubectl get pvc.

**Detailed Description**

![image](https://user-images.githubusercontent.com/13549903/197783042-68e82719-d56d-43cd-b693-3572752a9441.png)

**Anything else you would like to add:**

Should we consider updating the pPVC status synchronously to the pPVC?

/kind feature

**Comment by wondywang** [comment]
> 

Yes，At present, the PVC status.capacity is updated by the CSI driver after allocating storage space. and now after the spec.requests.storage of the PVC is updated in the VC, it is synchronized to the super, and then the PVC status on the super is updated by the CSI driver, but the status in the VC has not been updated.

**Comment by Fei-Guo** [comment]
Sure. Then adding uws makes sense.  Btw, I did not get this part " an exception when kubectl get pvc." .  What is the error?

**Comment by wondywang** [comment]
> Sure. Then adding pvc uws makes sense. Btw, I did not get this part " an exception when kubectl get pvc." . What is the error?

```bash
$ kubectl get pvc data0-kafka-1 -n confluent
NAME            STATUS   VOLUME                   CAPACITY   ACCESS MODES   STORAGECLASS                  AGE
data0-1         Bound       d-2zexxxxxxxxxxxxxx   1000Gi           RWO            storageclass-name                13d
```

It will show like this, capacity is displayed incorrectly. But in fact, the storage of PVC has been updated.
