### ISSUE TITLE
Create Controller and types for NestedControllerManager

### ISSUE THREAD

**Issue by christopherhein** [kubernetes-sigs/cluster-api-provider-nested#34]
https://github.com/kubernetes-sigs/cluster-api-provider-nested/pull/29

**Comment by christopherhein** [comment]
@charleszheng44 are you assigned and working on this?

**Comment by charleszheng44** [comment]
> @charleszheng44 are you assigned and working on this?

Yes, I am working on the NKAS and NKCM controller. The PR will be ready by the end of this week

**Comment by christopherhein** [comment]
/close 

This was implemented in #40
