### ISSUE TITLE
Unable to init Cluster with the nested  provider

### ISSUE THREAD

**Issue by lusche** [kubernetes-sigs/cluster-api-provider-nested#343]
**What steps did you take and what happened:**
Following the documentation https://github.com/kubernetes-sigs/cluster-api-provider-nested/tree/main/docs and try to init a cluster:
bin/clusterctl init --core cluster-api:v0.4.0  --control-plane nested:v0.1.0  --infrastructure nested:v0.1.0
Fetching providers
Error: current version of clusterctl is only compatible with v1beta1 providers, detected v1alpha4 for provider cluster-api

we get this error.  We tried the latest clusterctl version 1.3.5 as well as download the code and build the master tree. Same result in all tested binaries.

**What did you expect to happen:**
If i follow the documentation i would expact the same results as in the documenttion. S in this case a yaml that can be applied to a kubernets cluster.

**Environment:**

- cluster-api-provider-nested version: v0.1.0
- Minikube version :v1.23.2
- Kubernetes version: (use `kubectl version`): v1.26.3
- OS (e.g. from `/etc/os-release`): Debian GNU/Linux 11 (bullseye)

/kind bug

**Comment by groundnuty** [comment]
Encountered the same problem. I tried against many clusterctl versions with no luck. Please helo.
