### ISSUE TITLE
Consider archiving this repo

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api-provider-nested#360]
If I look at this repo, it seems that unfortunately this idea never took off:

- This provider never created a release, and there is on a v0.1.0 tag.
- Last commit is from 10m ago
- E2E test are failing since a long time (https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-nested#periodic-cluster-api-provider-nested-test)
- Also the go.mod file is still using at K8s v0.21.9 and CAPI v0.4.0 (all EOL form a long time)

According to @vincepri , who is the person I know with more info about this topic, the nested provider can be archived.
I quite agree

Opinions?

cc @neolit123 @justinsb @vincepri from a SIG PoV
cc  @christopherhein @charleszheng44 @Fei-Guo @zhuangqh from the maintainer list

If there is agreement, prior art for archiving a repo: https://github.com/kubernetes/org/issues/5013

**Comment by neolit123** [comment]
i'm +1 to archive subprojects that are not active or never took off.

we don't have a requirement to say e.g. "10 months of subproject inactivity means archival", but to me it seems the tempo has slowed down here. last open PR is from April with zero comments:
https://github.com/kubernetes-sigs/cluster-api-provider-nested/pull/358
a couple of new issues were opened earlier in the year and got not responses.

unless the maintainer roster has a strong argument i propose a lazy consensus archival for the 16th of Sept 2024.
(that's ~10 days from now)

**Comment by neolit123** [comment]
notified the ML about this ticket:
https://groups.google.com/g/kubernetes-sig-cluster-lifecycle/c/34C70ogudv8

**Comment by vincepri** [comment]
+1 to decommission

**Comment by x85446** [comment]
We are actively using this project.    Currently we have a fork of it and have upgraded to the latest version of K8s.  We would welcome becoming a maintainer.

**Comment by fabriziopandini** [comment]
@x85446 could you provide some more context? What use cases are you using this project for? 
Why you did not step up before, at least helping in getting a first release out of the door?  

Also, at first sight, upgrading a k8s version alone can't probably make this provider usable with Cluster API, so I assume you are only using some part of it as a library, but I might be wrong.

Last but not least, IMO to qualify as a community project, It would be great to have some more users/maintainers from a few companies. Do you know someone else using it?

**Comment by neolit123** [comment]
i personally think it's too late for that and we shouldn't surface a group that forked the project but did not actively participate in maintaining it when it was needed. also interested to know more about the use case, though.

**Comment by edhemphill** [comment]
Lol. Well, our company did not exist at the time :) (we are not as large as VMWare or Apple and we don't have the luxury of having many open-source developers :). We just very recently forked the project b/c we are building a multi-tenancy K8s solution. We plan on putting our entire project back under an Apache 2 license.  We are *very* thankful for the contributions of everyone and the project as it is.

Either way we will continue to move forward with our own work. If you all are not interested or feel it's not appropriate for it to be under the K8s SIG umbrella we entirely understand and would take no offense.

**Comment by edhemphill** [comment]
Well here is our fork:

https://github.com/IzumaNetworks/cluster-api-provider-nested

Right now everything we did was to get it to run on 1.30 - which is in `modernize` branch. 

Our focus will be on improving virtualcluster security and decreasing the amount of overhead. If we don't receive additional guidance we will keep maintaining this fork. Once again, thanks to everyone! @ Fei Guo @christopherhein @m-messiah and the many others...

**Comment by neolit123** [comment]
/close
- https://github.com/kubernetes/org/issues/5194
