### ISSUE TITLE
Write a tutorial for new CAPN users

### ISSUE THREAD

**Issue by Fei-Guo** [kubernetes-sigs/cluster-api-provider-nested#52]
We need to provide a document to describe how to launch a pod base control plane from scratch.

**Comment by christopherhein** [comment]
That's fair, I'll file some issues for generating all the `clusterctl` needed manifests for CAPN to work with `clusterctl`.

**Comment by gyliu513** [comment]
Hope we can have the tutorial as soon as possible so that users can have a early try ;)

**Comment by christopherhein** [comment]
@gyliu513 check out https://github.com/kubernetes-sigs/cluster-api-provider-nested/blob/master/docs/README.md and make sure that works for you, if not could you file w/e issues you have. Thanks!
