### ISSUE TITLE
🌱 Add Release Prow Jobs

### ISSUE THREAD

**Issue by christopherhein** [kubernetes-sigs/cluster-api-provider-nested#60]
Prior to the first version being released we need to add to the `scripts/` dir the proper release scripts as well as setup Prow release jobs. For now we should have just CAPN covered, we'll eventually create separate jobs for virtualcluster releases.

TODOS:
- [x] https://github.com/kubernetes/k8s.io/pull/2123/ Request GCP Project
- [x] Setup `Makefile`
- [x] Add Image build `prow` jobs

**Comment by christopherhein** [comment]
@vincepri do you have any examples or guides in how other Cluster API Providers handle releases and what we need to setup? I believe we already have a lot of the tooling in-place but just need to wire it all together.

**Comment by vincepri** [comment]
For releases, we usually have a bunch of things setup:

- The Makefile targets to get the images built: https://github.com/kubernetes-sigs/cluster-api/blob/master/Makefile#L469-L577
  - There is a lot in here, you can probably remove a bunch of things given that CAPI builds releases multiple components as part of the release process.
- A cloudbuild job: https://github.com/kubernetes-sigs/cluster-api/blob/master/cloudbuild.yaml

The above was built on top of what the default Makefile was at the time we built the CAPI project with kubebuilder. If you need some sync time happy to jump on Zoom and chat about the steps.

There are also some bits to configure in `test-infra`, and in the `k/k8s.io` repositories.

**Comment by christopherhein** [comment]
@vincepri for the Cloudbuild job, do we need to make our own gcloud project or is this picked up via prow?

**Comment by vincepri** [comment]
@christopherhein Yes the setup is there, you'll also need to request a GCP project like the one in here https://github.com/kubernetes/k8s.io/tree/main/audit/projects/k8s-staging-cluster-api

**Comment by christopherhein** [comment]
Awesome, thanks that part is what I was missing!

**Comment by christopherhein** [comment]
I forgot I cleaned up the `Makefile` in the last PR adding Prow presubmits - https://github.com/kubernetes-sigs/cluster-api-provider-nested/blob/main/Makefile#L300-L351

**Comment by christopherhein** [comment]
This was completed across many PRs and testing.
