### ISSUE TITLE
❓ Investigate v1.20 kubelet Redirection API Deprecation

### ISSUE THREAD

**Issue by christopherhein** [kubernetes-sigs/cluster-api-provider-nested#69]
Redirection was removed which breaks the vn-agent when we upgrade, we should investigate if our APIs still function as they should or if we need to implement anything "new".

**Comment by Fei-Guo** [comment]
Interesting, what is the new design for streaming api?

**Comment by christopherhein** [comment]
> Interesting, what is the new design for streaming api?

The streaming api still exists, the change was mainly to remove returning a 302 redirect instead to always locally stream through the kubelet as I'm understanding that KEP.

**Comment by tallclair** [comment]
For context, here's the KEP behind the upstream change: https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/1558-streaming-proxy-redirects
