### ISSUE TITLE
Proposal for ControlPlane Custom Resources 

### ISSUE THREAD

**Issue by christopherhein** [kubernetes-sigs/cluster-api-provider-nested#7]
This should cover how the all the `Nested*` types work together.

**Comment by vincepri** [comment]
One little suggestion, for diagrams I'd suggest using PlantUML and reuse the build infrastructure we've got upstream https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/Makefile#L28

By running `make diagrams`, the directive generates all PlantUML diagrams under docs/** and places them right next to the PlantUML file, vscode also has a nice extension for it :)

**Comment by christopherhein** [comment]
great idea @vincepri
