### ISSUE TITLE
Consider how to handle shared instance with VC

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api-provider-nested#77]
This issue is migrate from https://github.com/kubernetes-sigs/multi-tenancy/issues/1502

### Issue description

With VC, all of the components installed in tenant cluster will be isolated, and the tenant cluster will have all resources for a specified application.

Here the question is there are some apps, which has a shared component, and the component will be shared by many apps. So with such apps, I was hoping I can install the shared component in the super cluster, but install other components for the app into tenant clusters, and I want all of the tenant cluster app can access the super cluster shared component, any comments for how can I achieve this?

I think with this model, I can also reduce the footprint for the supercluster as well, as I can abstract some common services and deploy them into the super cluster, and share it with all tenant clusters.

### Comments from @christopherhein 

Maybe we can take this question over to https://sigs.k8s.io/cluster-api-provider-nested.

Short answer is we do a bit of this, but it's slightly different we allow nested(virtual) clusters to operate on "real" super cluster Service clusterIPs so that we can have routable clusterIP ranges, this is done via a mutating admission webhook which acts as a proxy to the super cluster, we also have custom syncers written using this model - https://github.com/kubernetes-sigs/cluster-api-provider-nested/blob/main/virtualcluster/doc/customresource-syncer.md for CRDs that we expose only the implementation at the super cluster but want tenant clusters to be able to CRUD them.

**Comment by christopherhein** [comment]
Yeah, to add to that… 

Some other example of areas where I could see more of this is a centralized logging or metrics system so everyone didn't need to maintain their own. 

All that being said there is a downside to this to consider, VC does a lot to help make the super cluster really lightweight and easily replaceable, the more you break that model the more VC get's harder and less flexible. For example if you look at the experimental namespace two tier scheduler this is continuing to focus on making the tenant cluster the owner of the data and the implementation which allows us to have N light weight pod scheduling domains if one goes down the tenant cluster can still exist and can easily transfer workloads to another cluster in the fleet.

**Comment by gyliu513** [comment]
> https://github.com/kubernetes-sigs/cluster-api-provider-nested/blob/main/virtualcluster/doc/customresource-syncer.md for CRDs that we expose only the implementation at the super cluster but want tenant clusters to be able to CRUD them.

@christopherhein , thanks, this is the feature that I want. If we can expose some CRDs only on super cluster, then how about extending this to support other k8s resources :)

**Comment by christopherhein** [comment]
Yup, we do this as well. Some are just to create random actions for example because we don't have CAPI's ClusterResourceSet we use a "checker" within the confines as how the vc-syncer defines it to automatically make sure there is always X or Y admission webhook deployed into the tenant control plane.

**Comment by christopherhein** [comment]
The struggle is you have to write a lot of those extensions yourself cause of how vc syncs things you need make sure it supports that flow, we package our syncer w/ vc-syncer as a single code base but extend it to have the other custom components.

**Comment by gyliu513** [comment]
> For example if you look at the experimental namespace two tier scheduler this is continuing to focus on making the tenant cluster the owner of the data and the implementation which allows us to have N light weight pod scheduling domains if one goes down the tenant cluster can still exist and can easily transfer workloads to another cluster in the fleet.

@christopherhein For VC, I think there is only one scheduler in super cluster, but no in tenant cluster. Can you share more detail for what do you mean by `experimental namespace two tier scheduler`?

**Comment by christopherhein** [comment]
@gyliu513 do you feel like you've gotten the right information now and we can close this issue?
