### ISSUE TITLE
Fix golang-ci lint configuration exclude configuration

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-nested#80]
The exclude configuration `Using the variable on range scope (tc)|(rt)|(tt)|(test)|(testcase)|(testCase) in function literal` in `.golang.ci.yml` matches too many findings. 

Every finding which contains "rt", "tt", "test", .. is excluded.

For more context:
* [Fix PR in cluster-api](https://github.com/kubernetes-sigs/cluster-api/pull/4657)
* [Follow-up PR for migration doc](https://github.com/kubernetes-sigs/cluster-api/pull/4664)
* [Discussion in Slack](https://kubernetes.slack.com/archives/C8TSNPY4T/p1621871864043200)

**Comment by christopherhein** [comment]
thanks @sbueringer for opening this.
